### ISSUE TITLE
Vuetify grid system conflicting with bootstrap grid

### ISSUE THREAD

**Issue by tystol** [NetCoreTemplates/vuetify-spa#1]
I'm getting some weird layout issues due to the 'row' class that is applied by the vuetify `v-layout` component with the 'row' attribute applied, and bootstrap's 'row' class.

I noticed bootstrap was removed here: 469bad14be751aae6b3c869f776f02a958a6ff12
but added back in here: 1732a0dcf763eec8122046134de15a10eb0da1e6

Is there any need for bootstrap in this template? I've removed it and I can't see any ill effects so far.

**Comment by mythz** [comment]
Nope not needed for Vuetify, was just trying to have all SPA projects share similar deps, but if it's causing issues I'll remove it.

I've removed bootstrap and updated to use the latest npm deps in this commit https://github.com/NetCoreTemplates/vuetify-spa/commit/9855798aa556f7d4f3c4421088fc9d6d8b1fcbce

Which I've also published, so creating a new template should use the latest version.
