### ISSUE TITLE
Chrome debugging not working - issue with sourcemaps?

### ISSUE THREAD

**Issue by tystol** [NetCoreTemplates/vuetify-spa#2]
From a brand new `dotnet-new vuetify-spa VuetifyTest`, I'm trying to put a chrome devtools breakpoint in the typescript section of the Home.vue file, but can't seem to find the suitable file. Doing a ctrl-P, I get a range of matching files:

![image](https://user-images.githubusercontent.com/915391/55732748-1e5f7780-5a4f-11e9-98f6-687434ddcc77.png)

That bottom one (the plain Home.vue without cachebuster suffixes) shows as:

    __webpack_require__.r(__webpack_exports__);
    /* harmony import */ var _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Home.vue?vue&type=template&id=66dfbd26& */ "./src/home/Home.vue?vue&type=template&id=66dfbd26&");
    /* harmony import */ var _Home_vue_vue_type_script_lang_ts___WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./Home.vue?vue&type=script&lang=ts& */ "./src/home/Home.vue?vue&type=script&lang=ts&");
    /* empty/unused harmony star reexport *//* harmony import */ var _Home_vue_vue_type_style_index_0_lang_scss___WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./Home.vue?vue&type=style&index=0&lang=scss& */ "./src/home/Home.vue?vue&type=style&index=0&lang=scss&");
    /* harmony import */ var _node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../../node_modules/vue-loader/lib/runtime/componentNormalizer.js */ "./node_modules/vue-loader/lib/runtime/componentNormalizer.js");

    /* normalize component */

    var component = Object(_node_modules_vue_loader_lib_runtime_componentNormalizer_js__WEBPACK_IMPORTED_MODULE_3__["default"])(
    _Home_vue_vue_type_script_lang_ts___WEBPACK_IMPORTED_MODULE_1__["default"],
    _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__["render"],
    _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"],
    false,
    null,
    null,
    null
    
    )

    /* hot reload */
    if (true) {
    var api = __webpack_require__(/*! ./node_modules/vue-hot-reload-api/dist/index.js */ "./node_modules/vue-hot-reload-api/dist/index.js")
    api.install(__webpack_require__(/*! vue */ "./node_modules/vue/dist/vue.runtime.esm.js"))
    if (api.compatible) {
        module.hot.accept()
        if (!module.hot.data) {
        api.createRecord('66dfbd26', component.options)
        } else {
        api.reload('66dfbd26', component.options)
        }
        module.hot.accept(/*! ./Home.vue?vue&type=template&id=66dfbd26& */ "./src/home/Home.vue?vue&type=template&id=66dfbd26&", function(__WEBPACK_OUTDATED_DEPENDENCIES__) { /* harmony import */ _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./Home.vue?vue&type=template&id=66dfbd26& */ "./src/home/Home.vue?vue&type=template&id=66dfbd26&");
    (function () {
        api.rerender('66dfbd26', {
            render: _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__["render"],
            staticRenderFns: _Home_vue_vue_type_template_id_66dfbd26___WEBPACK_IMPORTED_MODULE_0__["staticRenderFns"]
        })
        })(__WEBPACK_OUTDATED_DEPENDENCIES__); })
    }
    }
    component.options.__file = "src/home/Home.vue"
    /* harmony default export */ __webpack_exports__["default"] = (component.exports);//# sourceURL=[module]
    //# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaG9tZS9Ib21lLnZ1ZT80YmFlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUE7QUFBbUY7QUFDM0I7QUFDTDtBQUNjOzs7QUFHakU7QUFDMEY7QUFDMUYsZ0JBQWdCLDJHQUFVO0FBQzFCLEVBQUUsMEVBQU07QUFDUixFQUFFLCtFQUFNO0FBQ1IsRUFBRSx3RkFBZTtBQUNqQjtBQUNBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTtBQUNBLElBQUksSUFBVTtBQUNkLFlBQVksbUJBQU8sQ0FBQyx3R0FBeUY7QUFDN0csY0FBYyxtQkFBTyxDQUFDLHVEQUFLO0FBQzNCO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsS0FBSztBQUNMO0FBQ0E7QUFDQSxzQkFBc0IscUdBQTJDLEVBQUU7QUFBQTtBQUNuRTtBQUNBLGdCQUFnQiwrRUFBTTtBQUN0Qix5QkFBeUIsd0ZBQWU7QUFDeEMsT0FBTztBQUNQLEtBQUs7QUFDTDtBQUNBO0FBQ0E7QUFDZSxnRiIsImZpbGUiOiIuL3NyYy9ob21lL0hvbWUudnVlLmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgcmVuZGVyLCBzdGF0aWNSZW5kZXJGbnMgfSBmcm9tIFwiLi9Ib21lLnZ1ZT92dWUmdHlwZT10ZW1wbGF0ZSZpZD02NmRmYmQyNiZcIlxuaW1wb3J0IHNjcmlwdCBmcm9tIFwiLi9Ib21lLnZ1ZT92dWUmdHlwZT1zY3JpcHQmbGFuZz10cyZcIlxuZXhwb3J0ICogZnJvbSBcIi4vSG9tZS52dWU/dnVlJnR5cGU9c2NyaXB0Jmxhbmc9dHMmXCJcbmltcG9ydCBzdHlsZTAgZnJvbSBcIi4vSG9tZS52dWU/dnVlJnR5cGU9c3R5bGUmaW5kZXg9MCZsYW5nPXNjc3MmXCJcblxuXG4vKiBub3JtYWxpemUgY29tcG9uZW50ICovXG5pbXBvcnQgbm9ybWFsaXplciBmcm9tIFwiIS4uLy4uL25vZGVfbW9kdWxlcy92dWUtbG9hZGVyL2xpYi9ydW50aW1lL2NvbXBvbmVudE5vcm1hbGl6ZXIuanNcIlxudmFyIGNvbXBvbmVudCA9IG5vcm1hbGl6ZXIoXG4gIHNjcmlwdCxcbiAgcmVuZGVyLFxuICBzdGF0aWNSZW5kZXJGbnMsXG4gIGZhbHNlLFxuICBudWxsLFxuICBudWxsLFxuICBudWxsXG4gIFxuKVxuXG4vKiBob3QgcmVsb2FkICovXG5pZiAobW9kdWxlLmhvdCkge1xuICB2YXIgYXBpID0gcmVxdWlyZShcIi9Vc2Vycy90eXNvbi9Db2RlL1Z1ZXRpZnlUZXN0L1Z1ZXRpZnlUZXN0L25vZGVfbW9kdWxlcy92dWUtaG90LXJlbG9hZC1hcGkvZGlzdC9pbmRleC5qc1wiKVxuICBhcGkuaW5zdGFsbChyZXF1aXJlKCd2dWUnKSlcbiAgaWYgKGFwaS5jb21wYXRpYmxlKSB7XG4gICAgbW9kdWxlLmhvdC5hY2NlcHQoKVxuICAgIGlmICghbW9kdWxlLmhvdC5kYXRhKSB7XG4gICAgICBhcGkuY3JlYXRlUmVjb3JkKCc2NmRmYmQyNicsIGNvbXBvbmVudC5vcHRpb25zKVxuICAgIH0gZWxzZSB7XG4gICAgICBhcGkucmVsb2FkKCc2NmRmYmQyNicsIGNvbXBvbmVudC5vcHRpb25zKVxuICAgIH1cbiAgICBtb2R1bGUuaG90LmFjY2VwdChcIi4vSG9tZS52dWU/dnVlJnR5cGU9dGVtcGxhdGUmaWQ9NjZkZmJkMjYmXCIsIGZ1bmN0aW9uICgpIHtcbiAgICAgIGFwaS5yZXJlbmRlcignNjZkZmJkMjYnLCB7XG4gICAgICAgIHJlbmRlcjogcmVuZGVyLFxuICAgICAgICBzdGF0aWNSZW5kZXJGbnM6IHN0YXRpY1JlbmRlckZuc1xuICAgICAgfSlcbiAgICB9KVxuICB9XG59XG5jb21wb25lbnQub3B0aW9ucy5fX2ZpbGUgPSBcInNyYy9ob21lL0hvbWUudnVlXCJcbmV4cG9ydCBkZWZhdWx0IGNvbXBvbmVudC5leHBvcnRzIl0sInNvdXJjZVJvb3QiOiIifQ==

The other ones are not much help either. eg. the top one (Home.vue?vbae) contains:

    import { render, staticRenderFns } from "./Home.vue?vue&type=template&id=66dfbd26&"
    import script from "./Home.vue?vue&type=script&lang=ts&"
    export * from "./Home.vue?vue&type=script&lang=ts&"
    import style0 from "./Home.vue?vue&type=style&index=0&lang=scss&"

    /* normalize component */
    import normalizer from "!../../node_modules/vue-loader/lib/runtime/componentNormalizer.js"
    var component = normalizer(
    script,
    render,
    staticRenderFns,
    false,
    null,
    null,
    null
    
    )

    /* hot reload */
    if (module.hot) {
    var api = require("/Users/tyson/Code/VuetifyTest/VuetifyTest/node_modules/vue-hot-reload-api/dist/index.js")
    api.install(require('vue'))
    if (api.compatible) {
        module.hot.accept()
        if (!module.hot.data) {
        api.createRecord('66dfbd26', component.options)
        } else {
        api.reload('66dfbd26', component.options)
        }
        module.hot.accept("./Home.vue?vue&type=template&id=66dfbd26&", function () {
        api.rerender('66dfbd26', {
            render: render,
            staticRenderFns: staticRenderFns
        })
        })
    }
    }
    component.options.__file = "src/home/Home.vue"
    export default component.exports

Any ideas how to get this working? I'm assuming it's an issue with source maps but don't have any idea where to start.

PS. I'm very new to Vue (and out of touch on front end tech in general) so my apologies if this is something obvious - I was hoping to submit a PR instead but am completely stuck.

**Comment by mythz** [comment]
It works for me.

Installed project with:

    $ web new vuetify-spa VuetifyTest

    $ cd VuetifyTest\VuetifyTest
    $ dotnet run

Open Web Inspector, I had to look for `HomeComponent` by hitting `CTRL+SHIFT+F` then typing in `HomeComponent`:

![image](https://user-images.githubusercontent.com/89361/55748055-ad4aa080-5a0b-11e9-8066-430e732d4d0f.png)

Then I'm able to set a debug breakpoint as normal:

![image](https://user-images.githubusercontent.com/89361/55747903-51801780-5a0b-11e9-87ac-d342f79687c6.png)
